management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
    enabled-by-default: false
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true