global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "api-test"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8080"]
        labels:
          application: "api-test"